[package]
name = "texhigh"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashers = "*"
toml = "^0.8"
clap = "~4"
regex = "1"
pest = "~2"
pest_derive = "2"
indexmap = "2"
config = "~0"
serde = { version = "1", features = ["derive"]}
serde_with = "3"
lazy_static = "1"
bitflags = "2"
log = "0"
env_logger = "0"
encoding_rs = "*"
codepage = "*"
winapi = { version = "*", features = ["winnls"]}
unicode-properties = "*"
unicode-blocks = "*"

# [profile.release]
# debug = true
