use rayon::prelude::*;

/// Return the BCP 47 code.
pub fn language(id: u16) -> Option<&'static str> {
    if id < 0x0400 {
        Some(MACOS_TABLE.par_iter().find_any(|&&(i, ..)| i == id)?.2)
    } else {
        Some(WINDOWS_TABLE.par_iter().find_any(|&&(i, ..)| i == id)?.2)
    }
}

/// Return the language name.
pub fn language_str(id: u16) -> Option<&'static str> {
    if id < 0x0400 {
        Some(MACOS_TABLE.par_iter().find_any(|&&(i, ..)| i == id)?.3)
    } else {
        Some(WINDOWS_TABLE.par_iter().find_any(|&&(i, ..)| i == id)?.3)
    }
}

// https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html
#[rustfmt::skip]
static MACOS_TABLE: &[(u16, PrimaryLanguage, &str, &str)] = &[
    (0, PrimaryLanguage::English, "en", "English"),
    (1, PrimaryLanguage::French, "fr", "French"),
    (2, PrimaryLanguage::German, "de", "German"),
    (3, PrimaryLanguage::Italian, "it", "Italian"),
    (4, PrimaryLanguage::Dutch, "nl", "Dutch"),
    (5, PrimaryLanguage::Swedish, "sv", "Swedish"),
    (6, PrimaryLanguage::Spanish, "es", "Spanish"),
    (7, PrimaryLanguage::Danish, "da", "Danish"),
    (8, PrimaryLanguage::Portuguese, "pt", "Portuguese"),
    (9, PrimaryLanguage::Norwegian, "nb", "Norwegian"),
    (10, PrimaryLanguage::Hebrew, "he", "Hebrew"),
    (11, PrimaryLanguage::Japanese, "ja", "Japanese"),
    (12, PrimaryLanguage::Arabic, "ar", "Arabic"),
    (13, PrimaryLanguage::Finnish, "fi", "Finnish"),
    (14, PrimaryLanguage::Greek, "el", "Greek"),
    (15, PrimaryLanguage::Icelandic, "is", "Icelandic"),
    (16, PrimaryLanguage::Maltese, "mt", "Maltese"),
    (17, PrimaryLanguage::Turkish, "tr", "Turkish"),
    (18, PrimaryLanguage::Croatian, "hr", "Croatian"),
    (19, PrimaryLanguage::Chinese, "zh-Hant", "Chinese (Traditional)"),
    (20, PrimaryLanguage::Urdu, "ur", "Urdu"),
    (21, PrimaryLanguage::Hindi, "hi", "Hindi"),
    (22, PrimaryLanguage::Thai, "th", "Thai"),
    (23, PrimaryLanguage::Korean, "ko", "Korean"),
    (24, PrimaryLanguage::Lithuanian, "lt", "Lithuanian"),
    (25, PrimaryLanguage::Polish, "pl", "Polish"),
    (26, PrimaryLanguage::Hungarian, "hu", "Hungarian"),
    (27, PrimaryLanguage::Estonian, "et", "Estonian"),
    (28, PrimaryLanguage::Latvian, "lv", "Latvian"),
    (29, PrimaryLanguage::Sami, "se", "Sami"),
    (30, PrimaryLanguage::Faroese, "fo", "Faroese"),
    (31, PrimaryLanguage::Farsi, "fa", "Farsi/Persian"),
    (32, PrimaryLanguage::Russian, "ru", "Russian"),
    (33, PrimaryLanguage::Chinese, "zh-Hans", "Chinese (Simplified)"),
    (34, PrimaryLanguage::Flemish, "nl", "Flemish"),
    (35, PrimaryLanguage::Irish, "ga", "Irish Gaelic"),
    (36, PrimaryLanguage::Albanian, "sq", "Albanian"),
    (37, PrimaryLanguage::Romanian, "ro", "Romanian"),
    (38, PrimaryLanguage::Czech, "cs", "Czech"),
    (39, PrimaryLanguage::Slovak, "sk", "Slovak"),
    (40, PrimaryLanguage::Slovenian, "sl", "Slovenian"),
    (41, PrimaryLanguage::Yiddish, "yi", "Yiddish"),
    (42, PrimaryLanguage::Serbian, "sr", "Serbian"),
    (43, PrimaryLanguage::Macedonian, "mk", "Macedonian"),
    (44, PrimaryLanguage::Bulgarian, "bg", "Bulgarian"),
    (45, PrimaryLanguage::Ukrainian, "uk", "Ukrainian"),
    (46, PrimaryLanguage::Byelorussian, "be", "Byelorussian"),
    (47, PrimaryLanguage::Uzbek, "uz", "Uzbek"),
    (48, PrimaryLanguage::Kazakh, "kk", "Kazakh"),
    (49, PrimaryLanguage::Azerbaijani, "az-Cyrl", "Azerbaijani (Cyrillic script)"),
    (50, PrimaryLanguage::Azerbaijani, "az-Arab", "Azerbaijani (Arabic script)"),
    (51, PrimaryLanguage::Armenian, "hy", "Armenian"),
    (52, PrimaryLanguage::Georgian, "ka", "Georgian"),
    (53, PrimaryLanguage::Moldavian, "mo", "Moldavian"),
    (54, PrimaryLanguage::Kirghiz, "ky", "Kirghiz"),
    (55, PrimaryLanguage::Tajiki, "tg", "Tajiki"),
    (56, PrimaryLanguage::Turkmen, "tk", "Turkmen"),
    (57, PrimaryLanguage::Mongolian, "mn-Mong", "Mongolian (Mongolian script)"),
    (58, PrimaryLanguage::Mongolian, "mn-Cyrl", "Mongolian (Cyrillic script)"),
    (59, PrimaryLanguage::Pashto, "ps", "Pashto"),
    (60, PrimaryLanguage::Kurdish, "ku", "Kurdish"),
    (61, PrimaryLanguage::Kashmiri, "ks", "Kashmiri"),
    (62, PrimaryLanguage::Sindhi, "sd", "Sindhi"),
    (63, PrimaryLanguage::Tibetan, "bo", "Tibetan"),
    (64, PrimaryLanguage::Nepali, "ne", "Nepali"),
    (65, PrimaryLanguage::Sanskrit, "sa", "Sanskrit"),
    (66, PrimaryLanguage::Marathi, "mr", "Marathi"),
    (67, PrimaryLanguage::Bengali, "bn", "Bengali"),
    (68, PrimaryLanguage::Assamese, "as", "Assamese"),
    (69, PrimaryLanguage::Gujarati, "gu", "Gujarati"),
    (70, PrimaryLanguage::Punjabi, "pa", "Punjabi"),
    (71, PrimaryLanguage::Oriya, "or", "Oriya"),
    (72, PrimaryLanguage::Malayalam, "ml", "Malayalam"),
    (73, PrimaryLanguage::Kannada, "kn", "Kannada"),
    (74, PrimaryLanguage::Tamil, "ta", "Tamil"),
    (75, PrimaryLanguage::Telugu, "te", "Telugu"),
    (76, PrimaryLanguage::Sinhalese, "si", "Sinhalese"),
    (77, PrimaryLanguage::Burmese, "my", "Burmese"),
    (78, PrimaryLanguage::Khmer, "km", "Khmer"),
    (79, PrimaryLanguage::Lao, "lo", "Lao"),
    (80, PrimaryLanguage::Vietnamese, "vi", "Vietnamese"),
    (81, PrimaryLanguage::Indonesian, "id", "Indonesian"),
    (82, PrimaryLanguage::Tagalog, "tl", "Tagalog"),
    (83, PrimaryLanguage::Malay, "ms-Latn", "Malay (Roman script)"),
    (84, PrimaryLanguage::Malay, "ms-Arab", "Malay (Arabic script)"),
    (85, PrimaryLanguage::Amharic, "am", "Amharic"),
    (86, PrimaryLanguage::Tigrinya, "ti", "Tigrinya"),
    (87, PrimaryLanguage::Galla, "om", "Galla"),
    (88, PrimaryLanguage::Somali, "so", "Somali"),
    (89, PrimaryLanguage::Swahili, "sw", "Swahili"),
    (90, PrimaryLanguage::Kinyarwanda, "rw", "Kinyarwanda/Ruanda"),
    (91, PrimaryLanguage::Rundi, "rn", "Rundi"),
    (92, PrimaryLanguage::Nyanja, "ny", "Nyanja/Chewa"),
    (93, PrimaryLanguage::Malagasy, "mg", "Malagasy"),
    (94, PrimaryLanguage::Esperanto, "eo", "Esperanto"),
    (128, PrimaryLanguage::Welsh, "cy", "Welsh"),
    (129, PrimaryLanguage::Basque, "eu", "Basque"),
    (130, PrimaryLanguage::Catalan, "ca", "Catalan"),
    (131, PrimaryLanguage::Latin, "la", "Latin"),
    (132, PrimaryLanguage::Quechua, "quz", "Quechua"),
    (133, PrimaryLanguage::Guarani, "gn", "Guarani"),
    (134, PrimaryLanguage::Aymara, "ay", "Aymara"),
    (135, PrimaryLanguage::Tatar, "tt", "Tatar"),
    (136, PrimaryLanguage::Uighur, "ug", "Uighur"),
    (137, PrimaryLanguage::Dzongkha, "dz", "Dzongkha"),
    (138, PrimaryLanguage::Javanese, "jv-Latn", "Javanese (Roman script)"),
    (139, PrimaryLanguage::Sundanese, "su-Latn", "Sundanese (Roman script)"),
    (140, PrimaryLanguage::Galician, "gl", "Galician"),
    (141, PrimaryLanguage::Afrikaans, "af", "Afrikaans"),
    (142, PrimaryLanguage::Breton, "br", "Breton"),
    (143, PrimaryLanguage::Inuktitut, "iu", "Inuktitut"),
    (144, PrimaryLanguage::ScottishGaelic, "gd", "Scottish Gaelic"),
    (145, PrimaryLanguage::Manx, "gv", "Manx Gaelic"),
    (146, PrimaryLanguage::Irish, "ga", "Irish Gaelic (with dot above)"),
    (147, PrimaryLanguage::Tongan, "to", "Tongan"),
    (148, PrimaryLanguage::Greek, "el", "Greek (Polytonic)"),
    (149, PrimaryLanguage::Greenlandic, "kl", "Greenlandic"),
    (150, PrimaryLanguage::Azerbaijani, "az-Latn", "Azerbaijani (Roman script)"),
    (151, PrimaryLanguage::Norwegian, "nn", "Norwegian (Nynorsk)"),
];

// https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f
#[rustfmt::skip]
static WINDOWS_TABLE: &[(u16, Language, &str, &str, &str)] = &[
    (0x0401, Language::Arabic_SaudiArabia, "ar-SA", "Arabic", "Saudi Arabia"),
    (0x0402, Language::Bulgarian_Bulgaria, "bg-BG", "Bulgarian", "Bulgaria"),
    (0x0403, Language::Catalan_Catalan, "ca-ES", "Catalan", "Catalan"),
    (0x0404, Language::Chinese_Traditional_Taiwan, "zh-TW", "Chinese (Traditional)", "Taiwan"),
    (0x0405, Language::Czech_CzechRepublic, "cs-CZ", "Czech", "Czech Republic"),
    (0x0406, Language::Danish_Denmark, "da-DK", "Danish", "Denmark"),
    (0x0407, Language::German_Germany, "de-DE", "German", "Germany"),
    (0x0408, Language::Greek_Greece, "el-GR", "Greek", "Greece"),
    (0x0409, Language::English_UnitedStates, "en-US", "English", "United States"),
    (0x040A, Language::Spanish_TraditionalSort_Spain, "es-ES_tradnl", "Spanish (Traditional Sort)", "Spain"),
    (0x040B, Language::Finnish_Finland, "fi-FI", "Finnish", "Finland"),
    (0x040C, Language::French_France, "fr-FR", "French", "France"),
    (0x040D, Language::Hebrew_Israel, "he-IL", "Hebrew", "Israel"),
    (0x040E, Language::Hungarian_Hungary, "hu-HU", "Hungarian", "Hungary"),
    (0x040F, Language::Icelandic_Iceland, "is-IS", "Icelandic", "Iceland"),
    (0x0410, Language::Italian_Italy, "it-IT", "Italian", "Italy"),
    (0x0411, Language::Japanese_Japan, "ja-JP", "Japanese", "Japan"),
    (0x0412, Language::Korean_Korea, "ko-KR", "Korean", "Korea"),
    (0x0413, Language::Dutch_Netherlands, "nl-NL", "Dutch", "Netherlands"),
    (0x0414, Language::Norwegian_Bokmal_Norway, "nb-NO", "Norwegian (Bokmal)", "Norway"),
    (0x0415, Language::Polish_Poland, "pl-PL", "Polish", "Poland"),
    (0x0416, Language::Portuguese_Brazil, "pt-BR", "Portuguese", "Brazil"),
    (0x0417, Language::Romansh_Switzerland, "rm-CH", "Romansh", "Switzerland"),
    (0x0418, Language::Romanian_Romania, "ro-RO", "Romanian", "Romania"),
    (0x0419, Language::Russian_Russia, "ru-RU", "Russian", "Russia"),
    (0x041A, Language::Croatian_Croatia, "hr-HR", "Croatian", "Croatia"),
    (0x041B, Language::Slovak_Slovakia, "sk-SK", "Slovak", "Slovakia"),
    (0x041C, Language::Albanian_Albania, "sq-AL", "Albanian", "Albania"),
    (0x041D, Language::Swedish_Sweden, "sv-SE", "Swedish", "Sweden"),
    (0x041E, Language::Thai_Thailand, "th-TH", "Thai", "Thailand"),
    (0x041F, Language::Turkish_Turkey, "tr-TR", "Turkish", "Turkey"),
    (0x0420, Language::Urdu_IslamicRepublicOfPakistan, "ur-PK", "Urdu", "Islamic Republic of Pakistan"),
    (0x0421, Language::Indonesian_Indonesia, "id-ID", "Indonesian", "Indonesia"),
    (0x0422, Language::Ukrainian_Ukraine, "uk-UA", "Ukrainian", "Ukraine"),
    (0x0423, Language::Belarusian_Belarus, "be-BY", "Belarusian", "Belarus"),
    (0x0424, Language::Slovenian_Slovenia, "sl-SI", "Slovenian", "Slovenia"),
    (0x0425, Language::Estonian_Estonia, "et-EE", "Estonian", "Estonia"),
    (0x0426, Language::Latvian_Latvia, "lv-LV", "Latvian", "Latvia"),
    (0x0427, Language::Lithuanian_Lithuania, "lt-LT", "Lithuanian", "Lithuania"),
    (0x0428, Language::Tajik_Cyrillic_Tajikistan, "tg-Cyrl-TJ", "Tajik (Cyrillic)", "Tajikistan"),
    (0x0429, Language::Persian_Farsi_Iran, "fa-IR", "Persian (Farsi)", "Iran"),
    (0x042A, Language::Vietnamese_Vietnam, "vi-VN", "Vietnamese", "Vietnam"),
    (0x042B, Language::Armenian_Armenia, "hy-AM", "Armenian", "Armenia"),
    (0x042C, Language::Azeri_Latin_Azerbaijan, "az-Latn-AZ", "Azeri (Latin)", "Azerbaijan"),
    (0x042D, Language::Basque_Basque, "eu-ES", "Basque", "Basque"),
    (0x042E, Language::UpperSorbian_Germany, "hsb-DE", "Upper Sorbian", "Germany"),
    (0x042F, Language::Macedonian_NorthMacedonia, "mk-MK", "Macedonian", "North Macedonia"),
    (0x0432, Language::Setswana_SouthAfrica, "tn-ZA", "Setswana", "South Africa"),
    (0x0434, Language::isiXhosa_SouthAfrica, "xh-ZA", "isiXhosa", "South Africa"),
    (0x0435, Language::isiZulu_SouthAfrica, "zu-ZA", "isiZulu", "South Africa"),
    (0x0436, Language::Afrikaans_SouthAfrica, "af-ZA", "Afrikaans", "South Africa"),
    (0x0437, Language::Georgian_Georgia, "ka-GE", "Georgian", "Georgia"),
    (0x0438, Language::Faroese_FaroeIslands, "fo-FO", "Faroese", "Faroe Islands"),
    (0x0439, Language::Hindi_India, "hi-IN", "Hindi", "India"),
    (0x043A, Language::Maltese_Malta, "mt-MT", "Maltese", "Malta"),
    (0x043B, Language::Sami_Northern_Norway, "se-NO", "Sami (Northern)", "Norway"),
    (0x043D, Language::Yiddish_World, "yi-001", "Yiddish", "World"),
    (0x043E, Language::Malay_Malaysia, "ms-MY", "Malay", "Malaysia"),
    (0x043F, Language::Kazakh_Kazakhstan, "kk-KZ", "Kazakh", "Kazakhstan"),
    (0x0440, Language::Kyrgyz_Kyrgyzstan, "ky-KG", "Kyrgyz", "Kyrgyzstan"),
    (0x0441, Language::Kiswahili_Kenya, "sw-KE", "Kiswahili", "Kenya"),
    (0x0442, Language::Turkmen_Turkmenistan, "tk-TM", "Turkmen", "Turkmenistan"),
    (0x0443, Language::Uzbek_Latin_Uzbekistan, "uz-Latn-UZ", "Uzbek (Latin)", "Uzbekistan"),
    (0x0444, Language::Tatar_Russia, "tt-RU", "Tatar", "Russia"),
    (0x0445, Language::Bengali_India, "bn-IN", "Bengali", "Bangladesh and India"),
    (0x0446, Language::Punjabi_India, "pa-IN", "Punjabi", "India"),
    (0x0447, Language::Gujarati_India, "gu-IN", "Gujarati", "India"),
    (0x0448, Language::Odia_India, "or-IN", "Odia (formerly Oriya)", "India"),
    (0x0449, Language::Tamil_India, "ta-IN", "Tamil", "India"),
    (0x044A, Language::Telugu_India, "te-IN", "Telugu", "India"),
    (0x044B, Language::Kannada_India, "kn-IN", "Kannada", "India"),
    (0x044C, Language::Malayalam_India, "ml-IN", "Malayalam", "India"),
    (0x044D, Language::Assamese_India, "as-IN", "Assamese", "India"),
    (0x044E, Language::Marathi_India, "mr-IN", "Marathi", "India"),
    (0x044F, Language::Sanskrit_India, "sa-IN", "Sanskrit", "India"),
    (0x0450, Language::Mongolian_Cyrillic_Mongolia, "mn-Cyrl", "Mongolian (Cyrillic)", "Mongolia"),
    (0x0451, Language::Tibetan_PeoplesRepublicOfChina, "bo-CN", "Tibetan", "People's Republic of China"),
    (0x0452, Language::Welsh_UnitedKingdom, "cy-GB", "Welsh", "United Kingdom"),
    (0x0453, Language::Khmer_Cambodia, "km-KH", "Khmer", "Cambodia"),
    (0x0454, Language::Lao_LaoPDR, "lo-LA", "Lao", "Lao P.D.R."),
    (0x0456, Language::Galician_Galician, "gl-ES", "Galician", "Galician"),
    (0x0457, Language::Konkani_India, "kok-IN", "Konkani", "India"),
    (0x045A, Language::Syriac_Syria, "syr-SY", "Syriac", "Syria"),
    (0x045B, Language::Sinhala_SriLanka, "si-LK", "Sinhala", "Sri Lanka"),
    (0x045C, Language::Cherokee_Cherokee, "chr-Cher-US", "Cherokee", "Cherokee"),
    (0x045D, Language::Inuktitut_CanadianSyllabics_Canada, "iu-Cans-CA", "Inuktitut (Canadian Syllabics)", "Canada"),
    (0x045E, Language::Amharic_Ethiopia, "am-ET", "Amharic", "Ethiopia"),
    (0x0461, Language::Nepali_Nepal, "ne-NP", "Nepali", "Nepal"),
    (0x0462, Language::Frisian_Netherlands, "fy-NL", "Frisian", "Netherlands"),
    (0x0463, Language::Pashto_Afghanistan, "ps-AF", "Pashto", "Afghanistan"),
    (0x0464, Language::Filipino_Philippines, "fil-PH", "Filipino", "Philippines"),
    (0x0465, Language::Divehi_Maldives, "dv-MV", "Divehi", "Maldives"),
    (0x0468, Language::Hausa_Latin_Nigeria, "ha-Latn-NG", "Hausa (Latin)", "Nigeria"),
    (0x046A, Language::Yoruba_Nigeria, "yo-NG", "Yoruba", "Nigeria"),
    (0x046B, Language::Quechua_Bolivia, "quz-BO", "Quechua", "Bolivia"),
    (0x046C, Language::SesothoSaLeboa_SouthAfrica, "nso-ZA", "Sesotho sa Leboa", "South Africa"),
    (0x046D, Language::Bashkir_Russia, "ba-RU", "Bashkir", "Russia"),
    (0x046E, Language::Luxembourgish_Luxembourg, "lb-LU", "Luxembourgish", "Luxembourg"),
    (0x046F, Language::Greenlandic_Greenland, "kl-GL", "Greenlandic", "Greenland"),
    (0x0470, Language::Igbo_Nigeria, "ig-NG", "Igbo", "Nigeria"),
    (0x0473, Language::Tigrinya_Ethiopia, "ti-ET", "Tigrinya", "Ethiopia"),
    (0x0475, Language::Hawiian_UnitedStates, "haw-US", "Hawiian", "United States"),
    (0x0478, Language::Yi_PeoplesRepublicOfChina, "ii-CN", "Yi", "People's Republic of China"),
    (0x047A, Language::Mapudungun_Chile, "arn-CL", "Mapudungun", "Chile"),
    (0x047C, Language::Mohawk_Mohawk, "moh-CA", "Mohawk", "Mohawk"),
    (0x047E, Language::Breton_France, "br-FR", "Breton", "France"),
    (0x0480, Language::Uighur_PeoplesRepublicOfChina, "ug-CN", "Uighur", "People's Republic of China"),
    (0x0481, Language::Maori_NewZealand, "mi-NZ", "Maori", "New Zealand"),
    (0x0482, Language::Occitan_France, "oc-FR", "Occitan", "France"),
    (0x0483, Language::Corsican_France, "co-FR", "Corsican", "France"),
    (0x0484, Language::Alsatian_France, "gsw-FR", "Alsatian", "France"),
    (0x0485, Language::Yakut_Russia, "sah-RU", "Yakut", "Russia"),
    (0x0486, Language::Kiche_Guatemala, "qut-GT", "K'iche", "Guatemala"),
    (0x0487, Language::Kinyarwanda_Rwanda, "rw-RW", "Kinyarwanda", "Rwanda"),
    (0x0488, Language::Wolof_Senegal, "wo-SN", "Wolof", "Senegal"),
    (0x048C, Language::Dari_Afghanistan, "prs-AF", "Dari", "Afghanistan"),
    (0x0491, Language::ScottishGaelic_UnitedKingdom, "gd-GB", "Scottish Gaelic", "United Kingdom"),
    (0x0492, Language::CentralKurdish_Iraq, "ku-Arab-IQ", "Central Kurdish", "Iraq"),
    (0x0801, Language::Arabic_Iraq, "ar-IQ", "Arabic", "Iraq"),
    (0x0804, Language::Chinese_Simplified_PeoplesRepublicOfChina, "zh-Hans", "Chinese (Simplified)", "People's Republic of China"),
    (0x0807, Language::German_Switzerland, "de-CH", "German", "Switzerland"),
    (0x0809, Language::English_UnitedKingdom, "en-GB", "English", "United Kingdom"),
    (0x080A, Language::Spanish_Mexico, "es-MX", "Spanish", "Mexico"),
    (0x080C, Language::French_Belgium, "fr-BE", "French", "Belgium"),
    (0x0810, Language::Italian_Switzerland, "it-CH", "Italian", "Switzerland"),
    (0x0813, Language::Dutch_Belgium, "nl-BE", "Dutch", "Belgium"),
    (0x0814, Language::Norwegian_Nynorsk_Norway, "nn-NO", "Norwegian (Nynorsk)", "Norway"),
    (0x0816, Language::Portuguese_Portugal, "pt-PT", "Portuguese", "Portugal"),
    (0x081A, Language::Serbian_Latin_SerbiaAndMontenegro, "sr-Latn-CS", "Serbian (Latin)", "Serbia and Montenegro"),
    (0x081D, Language::Swedish_Finland, "sv-FI", "Swedish", "Finland"),
    (0x0820, Language::Urdu_India, "ur-IN", "Urdu", "India"),
    (0x082C, Language::Azeri_Cyrillic_Azerbaijan, "az-Cyrl-AZ", "Azeri (Cyrillic)", "Azerbaijan"),
    (0x082E, Language::LowerSorbian_Germany, "dsb-DE", "Lower Sorbian", "Germany"),
    (0x0832, Language::Setswana_Botswana, "tn-BW", "Setswana", "Botswana"),
    (0x083B, Language::Sami_Northern_Sweden, "se-SE", "Sami (Northern)", "Sweden"),
    (0x083C, Language::Irish_Ireland, "ga-IE", "Irish", "Ireland"),
    (0x083E, Language::Malay_BruneiDarussalam, "ms-BN", "Malay", "Brunei Darussalam"),
    (0x0843, Language::Uzbek_Cyrillic_Uzbekistan, "uz-Cyrl-UZ", "Uzbek (Cyrillic)", "Uzbekistan"),
    (0x0845, Language::Bengali_Bangladesh, "bn-BD", "Bengali", "Bangladesh"),
    (0x0846, Language::Punjabi_IslamicRepublicOfPakistan, "pa-Arab-PK", "Punjabi", "Islamic Republic of Pakistan"),
    (0x0849, Language::Tamil_SriLanka, "ta-LK", "Tamil", "SriLanka"),
    (0x0850, Language::Mongolian_Traditional_Mongolia, "mn-Mong-MN", "Mongolian (Traditional)", "Mongolia"),
    (0x0859, Language::Sindhi_IslamicRepublicOfPakistan, "sd-Arab-PK", "Sindhi", "Islamic Republic of Pakistan"),
    (0x085D, Language::Inuktitut_Latin_Canada, "iu-Latn-CA", "Inuktitut (Latin)", "Canada"),
    (0x085F, Language::Tamazight_Latin_Algeria, "tzm-Latn-DZ", "Tamazight (Latin)", "Algeria"),
    (0x086B, Language::Quechua_Ecuador, "quz-EC", "Quechua", "Ecuador"),
    (0x0873, Language::Tigrinya_Eritrea, "ti-ER", "Tigrinya", "Eritrea"),
    (0x0C01, Language::Arabic_Egypt, "ar-EG", "Arabic", "Egypt"),
    (0x0C04, Language::Chinese_HongKongSAR, "zh-Hant", "Chinese", "Hong Kong S.A.R."),
    (0x0C07, Language::German_Austria, "de-AT", "German", "Austria"),
    (0x0C09, Language::English_Australia, "en-AU", "English", "Australia"),
    (0x0C0A, Language::Spanish_ModernSort_Spain, "es-ES", "Spanish (Modern Sort)", "Spain"),
    (0x0C0C, Language::French_Canada, "fr-CA", "French", "Canada"),
    (0x0C1A, Language::Serbian_Cyrillic_SerbiaAndMontenegro, "sr-Cyrl-CS", "Serbian (Cyrillic)", "Serbia and Montenegro"),
    (0x0C3B, Language::Sami_Northern_Finland, "se-FI", "Sami (Northern)", "Finland"),
    (0x0C6B, Language::Quechua_Peru, "quz-PE", "Quechua", "Peru"),
    (0x1001, Language::Arabic_Libya, "ar-LY", "Arabic", "Libya"),
    (0x1004, Language::Chinese_Singapore, "zh-SG", "Chinese", "Singapore"),
    (0x1007, Language::German_Luxembourg, "de-LU", "German", "Luxembourg"),
    (0x1009, Language::English_Canada, "en-CA", "English", "Canada"),
    (0x100A, Language::Spanish_Guatemala, "es-GT", "Spanish", "Guatemala"),
    (0x100C, Language::French_Switzerland, "fr-CH", "French", "Switzerland"),
    (0x101A, Language::Croatian_Latin_BosniaAndHerzegovina, "hr-BA", "Croatian (Latin)", "Bosnia and Herzegovina"),
    (0x103B, Language::Sami_Lule_Norway, "smj-NO", "Sami (Lule)", "Norway"),
    (0x1401, Language::Arabic_Algeria, "ar-DZ", "Arabic", "Algeria"),
    (0x1404, Language::Chinese_MacaoSAR, "zh-MO", "Chinese", "Macao S.A.R."),
    (0x1407, Language::German_Liechtenstein, "de-LI", "German", "Liechtenstein"),
    (0x1409, Language::English_NewZealand, "en-NZ", "English", "New Zealand"),
    (0x140A, Language::Spanish_CostaRica, "es-CR", "Spanish", "Costa Rica"),
    (0x140c, Language::French_Luxembourg, "fr-LU", "French", "Luxembourg"),
    (0x141A, Language::Bosnian_Latin_BosniaAndHerzegovina, "bs-Latn-BA", "Bosnian (Latin)", "Bosnia and Herzegovina"),
    (0x143B, Language::Sami_Lule_Sweden, "smj-SE", "Sami (Lule)", "Sweden"),
    (0x105F, Language::CentralAtlasTamazight_Tifinagh_Morocco, "tzm-Tfng-MA", "Central Atlas Tamazight (Tifinagh)", "Morocco"),
    (0x1801, Language::Arabic_Morocco, "ar-MA", "Arabic", "Morocco"),
    (0x1809, Language::English_Ireland, "en-IE", "English", "Ireland"),
    (0x180A, Language::Spanish_Panama, "es-PA", "Spanish", "Panama"),
    (0x180C, Language::French_PrincipalityOfMonaco, "fr-MC", "French", "Principality of Monaco"),
    (0x181A, Language::Serbian_Latin_BosniaAndHerzegovina, "sr-Latn-BA", "Serbian (Latin)", "Bosnia and Herzegovina"),
    (0x183B, Language::Sami_Southern_Norway, "sma-NO", "Sami (Southern)", "Norway"),
    (0x1C01, Language::Arabic_Tunisia, "ar-TN", "Arabic", "Tunisia"),
    (0x1C09, Language::English_SouthAfrica, "en-ZA", "English", "South Africa"),
    (0x1C0A, Language::Spanish_DominicanRepublic, "es-DO", "Spanish", "Dominican Republic"),
    (0x1C1A, Language::Serbian_Cyrillic_BosniaAndHerzegovina, "sr-Cyrl-BA", "Serbian (Cyrillic)", "Bosnia and Herzegovina"),
    (0x1C3B, Language::Sami_Southern_Sweden, "sma-SE", "Sami (Southern)", "Sweden"),
    (0x2001, Language::Arabic_Oman, "ar-OM", "Arabic", "Oman"),
    (0x2009, Language::English_Jamaica, "en-JM", "English", "Jamaica"),
    (0x200A, Language::Spanish_Venezuela, "es-VE", "Spanish", "Venezuela"),
    (0x201A, Language::Bosnian_Cyrillic_BosniaAndHerzegovina, "bs-Cyrl-BA", "Bosnian (Cyrillic)", "Bosnia and Herzegovina"),
    (0x203B, Language::Sami_Skolt_Finland, "sms-FI", "Sami (Skolt)", "Finland"),
    (0x2401, Language::Arabic_Yemen, "ar-YE", "Arabic", "Yemen"),
    (0x2409, Language::English_Caribbean, "en-029", "English", "Caribbean"),
    (0x240A, Language::Spanish_Colombia, "es-CO", "Spanish", "Colombia"),
    (0x241A, Language::Serbian_Latin_Serbia, "sr-Latn-RS", "Serbian (Latin)", "Serbia"),
    (0x243B, Language::Sami_Inari_Finland, "smn-FI", "Sami (Inari)", "Finland"),
    (0x2801, Language::Arabic_Syria, "ar-SY", "Arabic", "Syria"),
    (0x2809, Language::English_Belize, "en-BZ", "English", "Belize"),
    (0x280A, Language::Spanish_Peru, "es-PE", "Spanish", "Peru"),
    (0x281A, Language::Serbian_Cyrillic_Serbia, "sr-Cyrl-RS", "Serbian (Cyrillic)", "Serbia"),
    (0x2C01, Language::Arabic_Jordan, "ar-JO", "Arabic", "Jordan"),
    (0x2C09, Language::English_TrinidadAndTobago, "en-TT", "English", "Trinidad and Tobago"),
    (0x2C0A, Language::Spanish_Argentina, "es-AR", "Spanish", "Argentina"),
    (0x2C1A, Language::Serbian_Latin_Montenegro, "sr-Latn-ME", "Serbian (Latin)", "Montenegro"),
    (0x3001, Language::Arabic_Lebanon, "ar-LB", "Arabic", "Lebanon"),
    (0x3009, Language::English_Zimbabwe, "en-ZW", "English", "Zimbabwe"),
    (0x300A, Language::Spanish_Ecuador, "es-EC", "Spanish", "Ecuador"),
    (0x301A, Language::Serbian_Cyrillic_Montenegro, "sr-Cyrl-ME", "Serbian (Cyrillic)", "Montenegro"),
    (0x3401, Language::Arabic_Kuwait, "ar-KW", "Arabic", "Kuwait"),
    (0x3409, Language::English_RepublicOfThePhilippines, "en-PH", "English", "Republic of the Philippines"),
    (0x340A, Language::Spanish_Chile, "es-CL", "Spanish", "Chile"),
    (0x3801, Language::Arabic_UAE, "ar-AE", "Arabic", "U.A.E."),
    (0x380A, Language::Spanish_Uruguay, "es-UY", "Spanish", "Uruguay"),
    (0x3C01, Language::Arabic_Bahrain, "ar-BH", "Arabic", "Bahrain"),
    (0x3C0A, Language::Spanish_Paraguay, "es-PY", "Spanish", "Paraguay"),
    (0x4001, Language::Arabic_Qatar, "ar-QA", "Arabic", "Qatar"),
    (0x4009, Language::English_India, "en-IN", "English", "India"),
    (0x400A, Language::Spanish_Bolivia, "es-BO", "Spanish", "Bolivia"),
    (0x4409, Language::English_Malaysia, "en-MY", "English", "Malaysia"),
    (0x440A, Language::Spanish_ElSalvador, "es-SV", "Spanish", "El Salvador"),
    (0x4809, Language::English_Singapore, "en-SG", "English", "Singapore"),
    (0x480A, Language::Spanish_Honduras, "es-HN", "Spanish", "Honduras"),
    (0x4C0A, Language::Spanish_Nicaragua, "es-NI", "Spanish", "Nicaragua"),
    (0x500A, Language::Spanish_PuertoRico, "es-PR", "Spanish", "Puerto Rico"),
    (0x540A, Language::Spanish_UnitedStates, "es-US", "Spanish", "United States"),
];

static LANGUAGE_PRIMARY: &[PrimaryLanguage] = &[
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Afrikaans,
    PrimaryLanguage::Albanian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Amharic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Arabic,
    PrimaryLanguage::Armenian,
    PrimaryLanguage::Assamese,
    PrimaryLanguage::Azerbaijani,
    PrimaryLanguage::Azerbaijani,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Byelorussian,
    PrimaryLanguage::Bengali,
    PrimaryLanguage::Bengali,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Breton,
    PrimaryLanguage::Bulgarian,
    PrimaryLanguage::Catalan,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Kurdish,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Chinese,
    PrimaryLanguage::Chinese,
    PrimaryLanguage::Chinese,
    PrimaryLanguage::Chinese,
    PrimaryLanguage::Chinese,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Croatian,
    PrimaryLanguage::Croatian,
    PrimaryLanguage::Czech,
    PrimaryLanguage::Danish,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Dutch,
    PrimaryLanguage::Dutch,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::English,
    PrimaryLanguage::Estonian,
    PrimaryLanguage::Faroese,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Finnish,
    PrimaryLanguage::French,
    PrimaryLanguage::French,
    PrimaryLanguage::French,
    PrimaryLanguage::French,
    PrimaryLanguage::French,
    PrimaryLanguage::French,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Galician,
    PrimaryLanguage::Georgian,
    PrimaryLanguage::German,
    PrimaryLanguage::German,
    PrimaryLanguage::German,
    PrimaryLanguage::German,
    PrimaryLanguage::German,
    PrimaryLanguage::Greek,
    PrimaryLanguage::Greenlandic,
    PrimaryLanguage::Gujarati,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Hebrew,
    PrimaryLanguage::Hindi,
    PrimaryLanguage::Hungarian,
    PrimaryLanguage::Icelandic,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Indonesian,
    PrimaryLanguage::Inuktitut,
    PrimaryLanguage::Inuktitut,
    PrimaryLanguage::Irish,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Italian,
    PrimaryLanguage::Italian,
    PrimaryLanguage::Japanese,
    PrimaryLanguage::Kannada,
    PrimaryLanguage::Kazakh,
    PrimaryLanguage::Khmer,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Kinyarwanda,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Korean,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Lao,
    PrimaryLanguage::Latvian,
    PrimaryLanguage::Lithuanian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Macedonian,
    PrimaryLanguage::Malay,
    PrimaryLanguage::Malay,
    PrimaryLanguage::Malayalam,
    PrimaryLanguage::Maltese,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Marathi,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Mongolian,
    PrimaryLanguage::Mongolian,
    PrimaryLanguage::Nepali,
    PrimaryLanguage::Norwegian,
    PrimaryLanguage::Norwegian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Pashto,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Polish,
    PrimaryLanguage::Portuguese,
    PrimaryLanguage::Portuguese,
    PrimaryLanguage::Punjabi,
    PrimaryLanguage::Punjabi,
    PrimaryLanguage::Quechua,
    PrimaryLanguage::Quechua,
    PrimaryLanguage::Quechua,
    PrimaryLanguage::Romanian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Russian,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sami,
    PrimaryLanguage::Sanskrit,
    PrimaryLanguage::ScottishGaelic,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Serbian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Sindhi,
    PrimaryLanguage::Sinhalese,
    PrimaryLanguage::Slovak,
    PrimaryLanguage::Slovenian,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Spanish,
    PrimaryLanguage::Swedish,
    PrimaryLanguage::Swedish,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Tajiki,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Tamil,
    PrimaryLanguage::Tamil,
    PrimaryLanguage::Tatar,
    PrimaryLanguage::Telugu,
    PrimaryLanguage::Thai,
    PrimaryLanguage::Tibetan,
    PrimaryLanguage::Tigrinya,
    PrimaryLanguage::Tigrinya,
    PrimaryLanguage::Turkish,
    PrimaryLanguage::Turkmen,
    PrimaryLanguage::Uighur,
    PrimaryLanguage::Ukrainian,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Urdu,
    PrimaryLanguage::Urdu,
    PrimaryLanguage::Uzbek,
    PrimaryLanguage::Uzbek,
    PrimaryLanguage::Vietnamese,
    PrimaryLanguage::Welsh,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Unknown,
    PrimaryLanguage::Yiddish,
    PrimaryLanguage::Unknown,
];

#[allow(non_camel_case_types)]
#[repr(u8)]
#[non_exhaustive]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Language {
    Unknown = 0,
    Afrikaans_SouthAfrica,
    Albanian_Albania,
    Alsatian_France,
    Amharic_Ethiopia,
    Arabic_Algeria,
    Arabic_Bahrain,
    Arabic_Egypt,
    Arabic_Iraq,
    Arabic_Jordan,
    Arabic_Kuwait,
    Arabic_Lebanon,
    Arabic_Libya,
    Arabic_Morocco,
    Arabic_Oman,
    Arabic_Qatar,
    Arabic_SaudiArabia,
    Arabic_Syria,
    Arabic_Tunisia,
    Arabic_UAE,
    Arabic_Yemen,
    Armenian_Armenia,
    Assamese_India,
    Azeri_Cyrillic_Azerbaijan,
    Azeri_Latin_Azerbaijan,
    Bashkir_Russia,
    Basque_Basque,
    Belarusian_Belarus,
    Bengali_Bangladesh,
    Bengali_India,
    Bosnian_Cyrillic_BosniaAndHerzegovina,
    Bosnian_Latin_BosniaAndHerzegovina,
    Breton_France,
    Bulgarian_Bulgaria,
    Catalan_Catalan,
    CentralAtlasTamazight_Tifinagh_Morocco,
    CentralKurdish_Iraq,
    Cherokee_Cherokee,
    Chinese_HongKongSAR,
    Chinese_MacaoSAR,
    Chinese_Simplified_PeoplesRepublicOfChina,
    Chinese_Singapore,
    Chinese_Traditional_Taiwan,
    Corsican_France,
    Croatian_Croatia,
    Croatian_Latin_BosniaAndHerzegovina,
    Czech_CzechRepublic,
    Danish_Denmark,
    Dari_Afghanistan,
    Divehi_Maldives,
    Dutch_Belgium,
    Dutch_Netherlands,
    English_Australia,
    English_Belize,
    English_Canada,
    English_Caribbean,
    English_India,
    English_Ireland,
    English_Jamaica,
    English_Malaysia,
    English_NewZealand,
    English_RepublicOfThePhilippines,
    English_Singapore,
    English_SouthAfrica,
    English_TrinidadAndTobago,
    English_UnitedKingdom,
    English_UnitedStates,
    English_Zimbabwe,
    Estonian_Estonia,
    Faroese_FaroeIslands,
    Filipino_Philippines,
    Finnish_Finland,
    French_Belgium,
    French_Canada,
    French_France,
    French_Luxembourg,
    French_PrincipalityOfMonaco,
    French_Switzerland,
    Frisian_Netherlands,
    Galician_Galician,
    Georgian_Georgia,
    German_Austria,
    German_Germany,
    German_Liechtenstein,
    German_Luxembourg,
    German_Switzerland,
    Greek_Greece,
    Greenlandic_Greenland,
    Gujarati_India,
    Hausa_Latin_Nigeria,
    Hawiian_UnitedStates,
    Hebrew_Israel,
    Hindi_India,
    Hungarian_Hungary,
    Icelandic_Iceland,
    Igbo_Nigeria,
    Indonesian_Indonesia,
    Inuktitut_CanadianSyllabics_Canada,
    Inuktitut_Latin_Canada,
    Irish_Ireland,
    isiXhosa_SouthAfrica,
    isiZulu_SouthAfrica,
    Italian_Italy,
    Italian_Switzerland,
    Japanese_Japan,
    Kannada_India,
    Kazakh_Kazakhstan,
    Khmer_Cambodia,
    Kiche_Guatemala,
    Kinyarwanda_Rwanda,
    Kiswahili_Kenya,
    Konkani_India,
    Korean_Korea,
    Kyrgyz_Kyrgyzstan,
    Lao_LaoPDR,
    Latvian_Latvia,
    Lithuanian_Lithuania,
    LowerSorbian_Germany,
    Luxembourgish_Luxembourg,
    Macedonian_NorthMacedonia,
    Malay_BruneiDarussalam,
    Malay_Malaysia,
    Malayalam_India,
    Maltese_Malta,
    Maori_NewZealand,
    Mapudungun_Chile,
    Marathi_India,
    Mohawk_Mohawk,
    Mongolian_Cyrillic_Mongolia,
    Mongolian_Traditional_Mongolia,
    Nepali_Nepal,
    Norwegian_Bokmal_Norway,
    Norwegian_Nynorsk_Norway,
    Occitan_France,
    Odia_India,
    Pashto_Afghanistan,
    Persian_Farsi_Iran,
    Polish_Poland,
    Portuguese_Brazil,
    Portuguese_Portugal,
    Punjabi_India,
    Punjabi_IslamicRepublicOfPakistan,
    Quechua_Bolivia,
    Quechua_Ecuador,
    Quechua_Peru,
    Romanian_Romania,
    Romansh_Switzerland,
    Russian_Russia,
    Sami_Inari_Finland,
    Sami_Lule_Norway,
    Sami_Lule_Sweden,
    Sami_Northern_Finland,
    Sami_Northern_Norway,
    Sami_Northern_Sweden,
    Sami_Skolt_Finland,
    Sami_Southern_Norway,
    Sami_Southern_Sweden,
    Sanskrit_India,
    ScottishGaelic_UnitedKingdom,
    Serbian_Cyrillic_BosniaAndHerzegovina,
    Serbian_Cyrillic_Montenegro,
    Serbian_Cyrillic_Serbia,
    Serbian_Cyrillic_SerbiaAndMontenegro,
    Serbian_Latin_BosniaAndHerzegovina,
    Serbian_Latin_Montenegro,
    Serbian_Latin_Serbia,
    Serbian_Latin_SerbiaAndMontenegro,
    SesothoSaLeboa_SouthAfrica,
    Setswana_Botswana,
    Setswana_SouthAfrica,
    Sindhi_IslamicRepublicOfPakistan,
    Sinhala_SriLanka,
    Slovak_Slovakia,
    Slovenian_Slovenia,
    Spanish_Argentina,
    Spanish_Bolivia,
    Spanish_Chile,
    Spanish_Colombia,
    Spanish_CostaRica,
    Spanish_DominicanRepublic,
    Spanish_Ecuador,
    Spanish_ElSalvador,
    Spanish_Guatemala,
    Spanish_Honduras,
    Spanish_Mexico,
    Spanish_ModernSort_Spain,
    Spanish_Nicaragua,
    Spanish_Panama,
    Spanish_Paraguay,
    Spanish_Peru,
    Spanish_PuertoRico,
    Spanish_TraditionalSort_Spain,
    Spanish_UnitedStates,
    Spanish_Uruguay,
    Spanish_Venezuela,
    Swedish_Finland,
    Swedish_Sweden,
    Syriac_Syria,
    Tajik_Cyrillic_Tajikistan,
    Tamazight_Latin_Algeria,
    Tamil_India,
    Tamil_SriLanka,
    Tatar_Russia,
    Telugu_India,
    Thai_Thailand,
    Tibetan_PeoplesRepublicOfChina,
    Tigrinya_Eritrea,
    Tigrinya_Ethiopia,
    Turkish_Turkey,
    Turkmen_Turkmenistan,
    Uighur_PeoplesRepublicOfChina,
    Ukrainian_Ukraine,
    UpperSorbian_Germany,
    Urdu_India,
    Urdu_IslamicRepublicOfPakistan,
    Uzbek_Cyrillic_Uzbekistan,
    Uzbek_Latin_Uzbekistan,
    Vietnamese_Vietnam,
    Welsh_UnitedKingdom,
    Wolof_Senegal,
    Yakut_Russia,
    Yi_PeoplesRepublicOfChina,
    Yiddish_World,
    Yoruba_Nigeria,
    ___END,
}

impl Language {
    /// Get the primary language.
    pub fn primary(&self) -> PrimaryLanguage {
        LANGUAGE_PRIMARY[*self as usize]
    }
    /// Return the BCP 47 code.
    pub fn to_str(&self) -> &'static str {
        match WINDOWS_TABLE.par_iter().find_any(|&&(_, l, ..)| l == *self) {
            Some(v) => v.2,
            None => "",
        }
    }
    /// Return the BCP 47 primary language.
    pub fn to_str_primary(&self) -> &'static str {
        let lang = self.to_str();
        match lang.find('-') {
            Some(idx) => &lang[0..idx],
            None => lang,
        }
    }
}

#[allow(non_camel_case_types)]
#[repr(u8)]
#[non_exhaustive]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum PrimaryLanguage {
    Unknown = 0,
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Armenian,
    Assamese,
    Aymara,
    Azerbaijani,
    Basque,
    Bengali,
    Breton,
    Bulgarian,
    Burmese,
    Byelorussian,
    Catalan,
    Chinese,
    Croatian,
    Czech,
    Danish,
    Dutch,
    Dzongkha,
    English,
    Esperanto,
    Estonian,
    Faroese,
    Farsi,
    Finnish,
    Flemish,
    French,
    Galician,
    Galla,
    Georgian,
    German,
    Greek,
    Greenlandic,
    Guarani,
    Gujarati,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Indonesian,
    Inuktitut,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kashmiri,
    Kazakh,
    Khmer,
    Kinyarwanda,
    Kirghiz,
    Korean,
    Kurdish,
    Lao,
    Latin,
    Latvian,
    Lithuanian,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Manx,
    Marathi,
    Moldavian,
    Mongolian,
    Nepali,
    Norwegian,
    Nyanja,
    Oriya,
    Pashto,
    Polish,
    Portuguese,
    Punjabi,
    Quechua,
    Romanian,
    Rundi,
    Russian,
    Sami,
    Sanskrit,
    ScottishGaelic,
    Serbian,
    Sindhi,
    Sinhalese,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tagalog,
    Tajiki,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tibetan,
    Tigrinya,
    Tongan,
    Turkish,
    Turkmen,
    Uighur,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Welsh,
    Yiddish,
    ___END,
}

impl PrimaryLanguage {
    /// Return the BCP 47 code.
    pub fn to_str(&self) -> &'static str {
        match MACOS_TABLE.par_iter().find_any(|&&(_, v, ..)| v == *self) {
            Some(v) => v.2,
            None => "",
        }
    }
    /// Return the BCP 47 primary language.
    pub fn to_str_primary(&self) -> &'static str {
        let lang = self.to_str();
        match lang.find('-') {
            Some(idx) => &lang[0..idx],
            None => lang,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem::transmute;

    #[test]
    fn lang_basic() {
        let max = Language::___END as u8;
        assert_eq!(max as usize, LANGUAGE_PRIMARY.len());
        for i in 0..max {
            let lang = unsafe { transmute::<u8, Language>(i) };
            let be_prim = lang.primary();
            print!("{:?}, {:?}. ", lang, be_prim);
            if be_prim == PrimaryLanguage::Unknown {
                println!("By pass");
            } else {
                println!("");
                let l_p = lang.to_str_primary();
                let b_p = be_prim.to_str_primary();
                if matches!(l_p, "nn" | "nb") && matches!(b_p, "nn" | "nb") {
                    // Norwegian: nn, nn-NO, nb-NO, nb-SJ
                } else if matches!(l_p, "smn" | "se" | "smj" | "sms" | "sma") && matches!(b_p, "se")
                {
                    // Sami: smn, smi-FI, smj, smj-NO, smj-SE, se, se-FI, se-NO, se-SE, sms, sms-FI, sma, sma-NO, sma-SE
                } else {
                    assert_eq!(l_p, b_p);
                }
            }
        }
    }
}
