use crate::range::NumberSpan;
use lazy_static::lazy_static;
use std::collections::HashMap;
use unicode_blocks as ub;

#[allow(dead_code)]
pub const VERSION: &'static str = ub::VERSION;
pub fn get_char_range_from_block_name(name: &str) -> Option<NumberSpan<char>> {
    match UNICODE_BLOCKS.get(&name) {
        Some(rng) => unsafe {
            let chr_start = char::from_u32_unchecked(rng[0]);
            let chr_end = char::from_u32_unchecked(rng[1]);
            Some((chr_start..=chr_end).into())
        },
        None => None,
    }
}

#[rustfmt::skip]
pub const fn get_cjk_ideographs_blocks() -> &'static [[u32; 2]; 12] { CJK_IDEOGRAPHS }

#[rustfmt::skip]
const CJK_IDEOGRAPHS: &'static [[u32; 2]; 12] = &[
    [ub::CJK_UNIFIED_IDEOGRAPHS.start(), ub::CJK_UNIFIED_IDEOGRAPHS.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H.end()],
    [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I.end()],
    [ub::CJK_COMPATIBILITY_IDEOGRAPHS.start(), ub::CJK_COMPATIBILITY_IDEOGRAPHS.end()],
    [ub::CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT.start(), ub::CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT.end()]
];

#[rustfmt::skip]
lazy_static! {
    pub static ref UNICODE_BLOCKS: HashMap<&'static str, [u32; 2]> = HashMap::from_iter([
        ("BASIC_LATIN", [ub::BASIC_LATIN.start(), ub::BASIC_LATIN.end()]),
        ("LATIN_1_SUPPLEMENT", [ub::LATIN_1_SUPPLEMENT.start(), ub::LATIN_1_SUPPLEMENT.end()]),
        ("LATIN_EXTENDED_A", [ub::LATIN_EXTENDED_A.start(), ub::LATIN_EXTENDED_A.end()]),
        ("LATIN_EXTENDED_B", [ub::LATIN_EXTENDED_B.start(), ub::LATIN_EXTENDED_B.end()]),
        ("IPA_EXTENSIONS", [ub::IPA_EXTENSIONS.start(), ub::IPA_EXTENSIONS.end()]),
        ("SPACING_MODIFIER_LETTERS", [ub::SPACING_MODIFIER_LETTERS.start(), ub::SPACING_MODIFIER_LETTERS.end()]),
        ("COMBINING_DIACRITICAL_MARKS", [ub::COMBINING_DIACRITICAL_MARKS.start(), ub::COMBINING_DIACRITICAL_MARKS.end()]),
        ("GREEK_AND_COPTIC", [ub::GREEK_AND_COPTIC.start(), ub::GREEK_AND_COPTIC.end()]),
        ("CYRILLIC", [ub::CYRILLIC.start(), ub::CYRILLIC.end()]),
        ("CYRILLIC_SUPPLEMENT", [ub::CYRILLIC_SUPPLEMENT.start(), ub::CYRILLIC_SUPPLEMENT.end()]),
        ("ARMENIAN", [ub::ARMENIAN.start(), ub::ARMENIAN.end()]),
        ("HEBREW", [ub::HEBREW.start(), ub::HEBREW.end()]),
        ("ARABIC", [ub::ARABIC.start(), ub::ARABIC.end()]),
        ("SYRIAC", [ub::SYRIAC.start(), ub::SYRIAC.end()]),
        ("ARABIC_SUPPLEMENT", [ub::ARABIC_SUPPLEMENT.start(), ub::ARABIC_SUPPLEMENT.end()]),
        ("THAANA", [ub::THAANA.start(), ub::THAANA.end()]),
        ("NKO", [ub::NKO.start(), ub::NKO.end()]),
        ("SAMARITAN", [ub::SAMARITAN.start(), ub::SAMARITAN.end()]),
        ("MANDAIC", [ub::MANDAIC.start(), ub::MANDAIC.end()]),
        ("SYRIAC_SUPPLEMENT", [ub::SYRIAC_SUPPLEMENT.start(), ub::SYRIAC_SUPPLEMENT.end()]),
        ("ARABIC_EXTENDED_B", [ub::ARABIC_EXTENDED_B.start(), ub::ARABIC_EXTENDED_B.end()]),
        ("ARABIC_EXTENDED_A", [ub::ARABIC_EXTENDED_A.start(), ub::ARABIC_EXTENDED_A.end()]),
        ("DEVANAGARI", [ub::DEVANAGARI.start(), ub::DEVANAGARI.end()]),
        ("BENGALI", [ub::BENGALI.start(), ub::BENGALI.end()]),
        ("GURMUKHI", [ub::GURMUKHI.start(), ub::GURMUKHI.end()]),
        ("GUJARATI", [ub::GUJARATI.start(), ub::GUJARATI.end()]),
        ("ORIYA", [ub::ORIYA.start(), ub::ORIYA.end()]),
        ("TAMIL", [ub::TAMIL.start(), ub::TAMIL.end()]),
        ("TELUGU", [ub::TELUGU.start(), ub::TELUGU.end()]),
        ("KANNADA", [ub::KANNADA.start(), ub::KANNADA.end()]),
        ("MALAYALAM", [ub::MALAYALAM.start(), ub::MALAYALAM.end()]),
        ("SINHALA", [ub::SINHALA.start(), ub::SINHALA.end()]),
        ("THAI", [ub::THAI.start(), ub::THAI.end()]),
        ("LAO", [ub::LAO.start(), ub::LAO.end()]),
        ("TIBETAN", [ub::TIBETAN.start(), ub::TIBETAN.end()]),
        ("MYANMAR", [ub::MYANMAR.start(), ub::MYANMAR.end()]),
        ("GEORGIAN", [ub::GEORGIAN.start(), ub::GEORGIAN.end()]),
        ("HANGUL_JAMO", [ub::HANGUL_JAMO.start(), ub::HANGUL_JAMO.end()]),
        ("ETHIOPIC", [ub::ETHIOPIC.start(), ub::ETHIOPIC.end()]),
        ("ETHIOPIC_SUPPLEMENT", [ub::ETHIOPIC_SUPPLEMENT.start(), ub::ETHIOPIC_SUPPLEMENT.end()]),
        ("CHEROKEE", [ub::CHEROKEE.start(), ub::CHEROKEE.end()]),
        ("UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS", [ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS.start(), ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS.end()]),
        ("OGHAM", [ub::OGHAM.start(), ub::OGHAM.end()]),
        ("RUNIC", [ub::RUNIC.start(), ub::RUNIC.end()]),
        ("TAGALOG", [ub::TAGALOG.start(), ub::TAGALOG.end()]),
        ("HANUNOO", [ub::HANUNOO.start(), ub::HANUNOO.end()]),
        ("BUHID", [ub::BUHID.start(), ub::BUHID.end()]),
        ("TAGBANWA", [ub::TAGBANWA.start(), ub::TAGBANWA.end()]),
        ("KHMER", [ub::KHMER.start(), ub::KHMER.end()]),
        ("MONGOLIAN", [ub::MONGOLIAN.start(), ub::MONGOLIAN.end()]),
        ("UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED", [ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED.start(), ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED.end()]),
        ("LIMBU", [ub::LIMBU.start(), ub::LIMBU.end()]),
        ("TAI_LE", [ub::TAI_LE.start(), ub::TAI_LE.end()]),
        ("NEW_TAI_LUE", [ub::NEW_TAI_LUE.start(), ub::NEW_TAI_LUE.end()]),
        ("KHMER_SYMBOLS", [ub::KHMER_SYMBOLS.start(), ub::KHMER_SYMBOLS.end()]),
        ("BUGINESE", [ub::BUGINESE.start(), ub::BUGINESE.end()]),
        ("TAI_THAM", [ub::TAI_THAM.start(), ub::TAI_THAM.end()]),
        ("COMBINING_DIACRITICAL_MARKS_EXTENDED", [ub::COMBINING_DIACRITICAL_MARKS_EXTENDED.start(), ub::COMBINING_DIACRITICAL_MARKS_EXTENDED.end()]),
        ("BALINESE", [ub::BALINESE.start(), ub::BALINESE.end()]),
        ("SUNDANESE", [ub::SUNDANESE.start(), ub::SUNDANESE.end()]),
        ("BATAK", [ub::BATAK.start(), ub::BATAK.end()]),
        ("LEPCHA", [ub::LEPCHA.start(), ub::LEPCHA.end()]),
        ("OL_CHIKI", [ub::OL_CHIKI.start(), ub::OL_CHIKI.end()]),
        ("CYRILLIC_EXTENDED_C", [ub::CYRILLIC_EXTENDED_C.start(), ub::CYRILLIC_EXTENDED_C.end()]),
        ("GEORGIAN_EXTENDED", [ub::GEORGIAN_EXTENDED.start(), ub::GEORGIAN_EXTENDED.end()]),
        ("SUNDANESE_SUPPLEMENT", [ub::SUNDANESE_SUPPLEMENT.start(), ub::SUNDANESE_SUPPLEMENT.end()]),
        ("VEDIC_EXTENSIONS", [ub::VEDIC_EXTENSIONS.start(), ub::VEDIC_EXTENSIONS.end()]),
        ("PHONETIC_EXTENSIONS", [ub::PHONETIC_EXTENSIONS.start(), ub::PHONETIC_EXTENSIONS.end()]),
        ("PHONETIC_EXTENSIONS_SUPPLEMENT", [ub::PHONETIC_EXTENSIONS_SUPPLEMENT.start(), ub::PHONETIC_EXTENSIONS_SUPPLEMENT.end()]),
        ("COMBINING_DIACRITICAL_MARKS_SUPPLEMENT", [ub::COMBINING_DIACRITICAL_MARKS_SUPPLEMENT.start(), ub::COMBINING_DIACRITICAL_MARKS_SUPPLEMENT.end()]),
        ("LATIN_EXTENDED_ADDITIONAL", [ub::LATIN_EXTENDED_ADDITIONAL.start(), ub::LATIN_EXTENDED_ADDITIONAL.end()]),
        ("GREEK_EXTENDED", [ub::GREEK_EXTENDED.start(), ub::GREEK_EXTENDED.end()]),
        ("GENERAL_PUNCTUATION", [ub::GENERAL_PUNCTUATION.start(), ub::GENERAL_PUNCTUATION.end()]),
        ("SUPERSCRIPTS_AND_SUBSCRIPTS", [ub::SUPERSCRIPTS_AND_SUBSCRIPTS.start(), ub::SUPERSCRIPTS_AND_SUBSCRIPTS.end()]),
        ("CURRENCY_SYMBOLS", [ub::CURRENCY_SYMBOLS.start(), ub::CURRENCY_SYMBOLS.end()]),
        ("COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS", [ub::COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS.start(), ub::COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS.end()]),
        ("LETTERLIKE_SYMBOLS", [ub::LETTERLIKE_SYMBOLS.start(), ub::LETTERLIKE_SYMBOLS.end()]),
        ("NUMBER_FORMS", [ub::NUMBER_FORMS.start(), ub::NUMBER_FORMS.end()]),
        ("ARROWS", [ub::ARROWS.start(), ub::ARROWS.end()]),
        ("MATHEMATICAL_OPERATORS", [ub::MATHEMATICAL_OPERATORS.start(), ub::MATHEMATICAL_OPERATORS.end()]),
        ("MISCELLANEOUS_TECHNICAL", [ub::MISCELLANEOUS_TECHNICAL.start(), ub::MISCELLANEOUS_TECHNICAL.end()]),
        ("CONTROL_PICTURES", [ub::CONTROL_PICTURES.start(), ub::CONTROL_PICTURES.end()]),
        ("OPTICAL_CHARACTER_RECOGNITION", [ub::OPTICAL_CHARACTER_RECOGNITION.start(), ub::OPTICAL_CHARACTER_RECOGNITION.end()]),
        ("ENCLOSED_ALPHANUMERICS", [ub::ENCLOSED_ALPHANUMERICS.start(), ub::ENCLOSED_ALPHANUMERICS.end()]),
        ("BOX_DRAWING", [ub::BOX_DRAWING.start(), ub::BOX_DRAWING.end()]),
        ("BLOCK_ELEMENTS", [ub::BLOCK_ELEMENTS.start(), ub::BLOCK_ELEMENTS.end()]),
        ("GEOMETRIC_SHAPES", [ub::GEOMETRIC_SHAPES.start(), ub::GEOMETRIC_SHAPES.end()]),
        ("MISCELLANEOUS_SYMBOLS", [ub::MISCELLANEOUS_SYMBOLS.start(), ub::MISCELLANEOUS_SYMBOLS.end()]),
        ("DINGBATS", [ub::DINGBATS.start(), ub::DINGBATS.end()]),
        ("MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A", [ub::MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A.start(), ub::MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A.end()]),
        ("SUPPLEMENTAL_ARROWS_A", [ub::SUPPLEMENTAL_ARROWS_A.start(), ub::SUPPLEMENTAL_ARROWS_A.end()]),
        ("BRAILLE_PATTERNS", [ub::BRAILLE_PATTERNS.start(), ub::BRAILLE_PATTERNS.end()]),
        ("SUPPLEMENTAL_ARROWS_B", [ub::SUPPLEMENTAL_ARROWS_B.start(), ub::SUPPLEMENTAL_ARROWS_B.end()]),
        ("MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B", [ub::MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B.start(), ub::MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B.end()]),
        ("SUPPLEMENTAL_MATHEMATICAL_OPERATORS", [ub::SUPPLEMENTAL_MATHEMATICAL_OPERATORS.start(), ub::SUPPLEMENTAL_MATHEMATICAL_OPERATORS.end()]),
        ("MISCELLANEOUS_SYMBOLS_AND_ARROWS", [ub::MISCELLANEOUS_SYMBOLS_AND_ARROWS.start(), ub::MISCELLANEOUS_SYMBOLS_AND_ARROWS.end()]),
        ("GLAGOLITIC", [ub::GLAGOLITIC.start(), ub::GLAGOLITIC.end()]),
        ("LATIN_EXTENDED_C", [ub::LATIN_EXTENDED_C.start(), ub::LATIN_EXTENDED_C.end()]),
        ("COPTIC", [ub::COPTIC.start(), ub::COPTIC.end()]),
        ("GEORGIAN_SUPPLEMENT", [ub::GEORGIAN_SUPPLEMENT.start(), ub::GEORGIAN_SUPPLEMENT.end()]),
        ("TIFINAGH", [ub::TIFINAGH.start(), ub::TIFINAGH.end()]),
        ("ETHIOPIC_EXTENDED", [ub::ETHIOPIC_EXTENDED.start(), ub::ETHIOPIC_EXTENDED.end()]),
        ("CYRILLIC_EXTENDED_A", [ub::CYRILLIC_EXTENDED_A.start(), ub::CYRILLIC_EXTENDED_A.end()]),
        ("SUPPLEMENTAL_PUNCTUATION", [ub::SUPPLEMENTAL_PUNCTUATION.start(), ub::SUPPLEMENTAL_PUNCTUATION.end()]),
        ("CJK_RADICALS_SUPPLEMENT", [ub::CJK_RADICALS_SUPPLEMENT.start(), ub::CJK_RADICALS_SUPPLEMENT.end()]),
        ("KANGXI_RADICALS", [ub::KANGXI_RADICALS.start(), ub::KANGXI_RADICALS.end()]),
        ("IDEOGRAPHIC_DESCRIPTION_CHARACTERS", [ub::IDEOGRAPHIC_DESCRIPTION_CHARACTERS.start(), ub::IDEOGRAPHIC_DESCRIPTION_CHARACTERS.end()]),
        ("CJK_SYMBOLS_AND_PUNCTUATION", [ub::CJK_SYMBOLS_AND_PUNCTUATION.start(), ub::CJK_SYMBOLS_AND_PUNCTUATION.end()]),
        ("HIRAGANA", [ub::HIRAGANA.start(), ub::HIRAGANA.end()]),
        ("KATAKANA", [ub::KATAKANA.start(), ub::KATAKANA.end()]),
        ("BOPOMOFO", [ub::BOPOMOFO.start(), ub::BOPOMOFO.end()]),
        ("HANGUL_COMPATIBILITY_JAMO", [ub::HANGUL_COMPATIBILITY_JAMO.start(), ub::HANGUL_COMPATIBILITY_JAMO.end()]),
        ("KANBUN", [ub::KANBUN.start(), ub::KANBUN.end()]),
        ("BOPOMOFO_EXTENDED", [ub::BOPOMOFO_EXTENDED.start(), ub::BOPOMOFO_EXTENDED.end()]),
        ("CJK_STROKES", [ub::CJK_STROKES.start(), ub::CJK_STROKES.end()]),
        ("KATAKANA_PHONETIC_EXTENSIONS", [ub::KATAKANA_PHONETIC_EXTENSIONS.start(), ub::KATAKANA_PHONETIC_EXTENSIONS.end()]),
        ("ENCLOSED_CJK_LETTERS_AND_MONTHS", [ub::ENCLOSED_CJK_LETTERS_AND_MONTHS.start(), ub::ENCLOSED_CJK_LETTERS_AND_MONTHS.end()]),
        ("CJK_COMPATIBILITY", [ub::CJK_COMPATIBILITY.start(), ub::CJK_COMPATIBILITY.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A.end()]),
        ("YIJING_HEXAGRAM_SYMBOLS", [ub::YIJING_HEXAGRAM_SYMBOLS.start(), ub::YIJING_HEXAGRAM_SYMBOLS.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS", [ub::CJK_UNIFIED_IDEOGRAPHS.start(), ub::CJK_UNIFIED_IDEOGRAPHS.end()]),
        ("YI_SYLLABLES", [ub::YI_SYLLABLES.start(), ub::YI_SYLLABLES.end()]),
        ("YI_RADICALS", [ub::YI_RADICALS.start(), ub::YI_RADICALS.end()]),
        ("LISU", [ub::LISU.start(), ub::LISU.end()]),
        ("VAI", [ub::VAI.start(), ub::VAI.end()]),
        ("CYRILLIC_EXTENDED_B", [ub::CYRILLIC_EXTENDED_B.start(), ub::CYRILLIC_EXTENDED_B.end()]),
        ("BAMUM", [ub::BAMUM.start(), ub::BAMUM.end()]),
        ("MODIFIER_TONE_LETTERS", [ub::MODIFIER_TONE_LETTERS.start(), ub::MODIFIER_TONE_LETTERS.end()]),
        ("LATIN_EXTENDED_D", [ub::LATIN_EXTENDED_D.start(), ub::LATIN_EXTENDED_D.end()]),
        ("SYLOTI_NAGRI", [ub::SYLOTI_NAGRI.start(), ub::SYLOTI_NAGRI.end()]),
        ("COMMON_INDIC_NUMBER_FORMS", [ub::COMMON_INDIC_NUMBER_FORMS.start(), ub::COMMON_INDIC_NUMBER_FORMS.end()]),
        ("PHAGS_PA", [ub::PHAGS_PA.start(), ub::PHAGS_PA.end()]),
        ("SAURASHTRA", [ub::SAURASHTRA.start(), ub::SAURASHTRA.end()]),
        ("DEVANAGARI_EXTENDED", [ub::DEVANAGARI_EXTENDED.start(), ub::DEVANAGARI_EXTENDED.end()]),
        ("KAYAH_LI", [ub::KAYAH_LI.start(), ub::KAYAH_LI.end()]),
        ("REJANG", [ub::REJANG.start(), ub::REJANG.end()]),
        ("HANGUL_JAMO_EXTENDED_A", [ub::HANGUL_JAMO_EXTENDED_A.start(), ub::HANGUL_JAMO_EXTENDED_A.end()]),
        ("JAVANESE", [ub::JAVANESE.start(), ub::JAVANESE.end()]),
        ("MYANMAR_EXTENDED_B", [ub::MYANMAR_EXTENDED_B.start(), ub::MYANMAR_EXTENDED_B.end()]),
        ("CHAM", [ub::CHAM.start(), ub::CHAM.end()]),
        ("MYANMAR_EXTENDED_A", [ub::MYANMAR_EXTENDED_A.start(), ub::MYANMAR_EXTENDED_A.end()]),
        ("TAI_VIET", [ub::TAI_VIET.start(), ub::TAI_VIET.end()]),
        ("MEETEI_MAYEK_EXTENSIONS", [ub::MEETEI_MAYEK_EXTENSIONS.start(), ub::MEETEI_MAYEK_EXTENSIONS.end()]),
        ("ETHIOPIC_EXTENDED_A", [ub::ETHIOPIC_EXTENDED_A.start(), ub::ETHIOPIC_EXTENDED_A.end()]),
        ("LATIN_EXTENDED_E", [ub::LATIN_EXTENDED_E.start(), ub::LATIN_EXTENDED_E.end()]),
        ("CHEROKEE_SUPPLEMENT", [ub::CHEROKEE_SUPPLEMENT.start(), ub::CHEROKEE_SUPPLEMENT.end()]),
        ("MEETEI_MAYEK", [ub::MEETEI_MAYEK.start(), ub::MEETEI_MAYEK.end()]),
        ("HANGUL_SYLLABLES", [ub::HANGUL_SYLLABLES.start(), ub::HANGUL_SYLLABLES.end()]),
        ("HANGUL_JAMO_EXTENDED_B", [ub::HANGUL_JAMO_EXTENDED_B.start(), ub::HANGUL_JAMO_EXTENDED_B.end()]),
        ("PRIVATE_USE_AREA", [ub::PRIVATE_USE_AREA.start(), ub::PRIVATE_USE_AREA.end()]),
        ("CJK_COMPATIBILITY_IDEOGRAPHS", [ub::CJK_COMPATIBILITY_IDEOGRAPHS.start(), ub::CJK_COMPATIBILITY_IDEOGRAPHS.end()]),
        ("ALPHABETIC_PRESENTATION_FORMS", [ub::ALPHABETIC_PRESENTATION_FORMS.start(), ub::ALPHABETIC_PRESENTATION_FORMS.end()]),
        ("ARABIC_PRESENTATION_FORMS_A", [ub::ARABIC_PRESENTATION_FORMS_A.start(), ub::ARABIC_PRESENTATION_FORMS_A.end()]),
        ("VARIATION_SELECTORS", [ub::VARIATION_SELECTORS.start(), ub::VARIATION_SELECTORS.end()]),
        ("VERTICAL_FORMS", [ub::VERTICAL_FORMS.start(), ub::VERTICAL_FORMS.end()]),
        ("COMBINING_HALF_MARKS", [ub::COMBINING_HALF_MARKS.start(), ub::COMBINING_HALF_MARKS.end()]),
        ("CJK_COMPATIBILITY_FORMS", [ub::CJK_COMPATIBILITY_FORMS.start(), ub::CJK_COMPATIBILITY_FORMS.end()]),
        ("SMALL_FORM_VARIANTS", [ub::SMALL_FORM_VARIANTS.start(), ub::SMALL_FORM_VARIANTS.end()]),
        ("ARABIC_PRESENTATION_FORMS_B", [ub::ARABIC_PRESENTATION_FORMS_B.start(), ub::ARABIC_PRESENTATION_FORMS_B.end()]),
        ("HALFWIDTH_AND_FULLWIDTH_FORMS", [ub::HALFWIDTH_AND_FULLWIDTH_FORMS.start(), ub::HALFWIDTH_AND_FULLWIDTH_FORMS.end()]),
        ("SPECIALS", [ub::SPECIALS.start(), ub::SPECIALS.end()]),
        ("LINEAR_B_SYLLABARY", [ub::LINEAR_B_SYLLABARY.start(), ub::LINEAR_B_SYLLABARY.end()]),
        ("LINEAR_B_IDEOGRAMS", [ub::LINEAR_B_IDEOGRAMS.start(), ub::LINEAR_B_IDEOGRAMS.end()]),
        ("AEGEAN_NUMBERS", [ub::AEGEAN_NUMBERS.start(), ub::AEGEAN_NUMBERS.end()]),
        ("ANCIENT_GREEK_NUMBERS", [ub::ANCIENT_GREEK_NUMBERS.start(), ub::ANCIENT_GREEK_NUMBERS.end()]),
        ("ANCIENT_SYMBOLS", [ub::ANCIENT_SYMBOLS.start(), ub::ANCIENT_SYMBOLS.end()]),
        ("PHAISTOS_DISC", [ub::PHAISTOS_DISC.start(), ub::PHAISTOS_DISC.end()]),
        ("LYCIAN", [ub::LYCIAN.start(), ub::LYCIAN.end()]),
        ("CARIAN", [ub::CARIAN.start(), ub::CARIAN.end()]),
        ("COPTIC_EPACT_NUMBERS", [ub::COPTIC_EPACT_NUMBERS.start(), ub::COPTIC_EPACT_NUMBERS.end()]),
        ("OLD_ITALIC", [ub::OLD_ITALIC.start(), ub::OLD_ITALIC.end()]),
        ("GOTHIC", [ub::GOTHIC.start(), ub::GOTHIC.end()]),
        ("OLD_PERMIC", [ub::OLD_PERMIC.start(), ub::OLD_PERMIC.end()]),
        ("UGARITIC", [ub::UGARITIC.start(), ub::UGARITIC.end()]),
        ("OLD_PERSIAN", [ub::OLD_PERSIAN.start(), ub::OLD_PERSIAN.end()]),
        ("DESERET", [ub::DESERET.start(), ub::DESERET.end()]),
        ("SHAVIAN", [ub::SHAVIAN.start(), ub::SHAVIAN.end()]),
        ("OSMANYA", [ub::OSMANYA.start(), ub::OSMANYA.end()]),
        ("OSAGE", [ub::OSAGE.start(), ub::OSAGE.end()]),
        ("ELBASAN", [ub::ELBASAN.start(), ub::ELBASAN.end()]),
        ("CAUCASIAN_ALBANIAN", [ub::CAUCASIAN_ALBANIAN.start(), ub::CAUCASIAN_ALBANIAN.end()]),
        ("VITHKUQI", [ub::VITHKUQI.start(), ub::VITHKUQI.end()]),
        ("LINEAR_A", [ub::LINEAR_A.start(), ub::LINEAR_A.end()]),
        ("LATIN_EXTENDED_F", [ub::LATIN_EXTENDED_F.start(), ub::LATIN_EXTENDED_F.end()]),
        ("CYPRIOT_SYLLABARY", [ub::CYPRIOT_SYLLABARY.start(), ub::CYPRIOT_SYLLABARY.end()]),
        ("IMPERIAL_ARAMAIC", [ub::IMPERIAL_ARAMAIC.start(), ub::IMPERIAL_ARAMAIC.end()]),
        ("PALMYRENE", [ub::PALMYRENE.start(), ub::PALMYRENE.end()]),
        ("NABATAEAN", [ub::NABATAEAN.start(), ub::NABATAEAN.end()]),
        ("HATRAN", [ub::HATRAN.start(), ub::HATRAN.end()]),
        ("PHOENICIAN", [ub::PHOENICIAN.start(), ub::PHOENICIAN.end()]),
        ("LYDIAN", [ub::LYDIAN.start(), ub::LYDIAN.end()]),
        ("MEROITIC_HIEROGLYPHS", [ub::MEROITIC_HIEROGLYPHS.start(), ub::MEROITIC_HIEROGLYPHS.end()]),
        ("MEROITIC_CURSIVE", [ub::MEROITIC_CURSIVE.start(), ub::MEROITIC_CURSIVE.end()]),
        ("KHAROSHTHI", [ub::KHAROSHTHI.start(), ub::KHAROSHTHI.end()]),
        ("OLD_SOUTH_ARABIAN", [ub::OLD_SOUTH_ARABIAN.start(), ub::OLD_SOUTH_ARABIAN.end()]),
        ("OLD_NORTH_ARABIAN", [ub::OLD_NORTH_ARABIAN.start(), ub::OLD_NORTH_ARABIAN.end()]),
        ("MANICHAEAN", [ub::MANICHAEAN.start(), ub::MANICHAEAN.end()]),
        ("AVESTAN", [ub::AVESTAN.start(), ub::AVESTAN.end()]),
        ("INSCRIPTIONAL_PARTHIAN", [ub::INSCRIPTIONAL_PARTHIAN.start(), ub::INSCRIPTIONAL_PARTHIAN.end()]),
        ("INSCRIPTIONAL_PAHLAVI", [ub::INSCRIPTIONAL_PAHLAVI.start(), ub::INSCRIPTIONAL_PAHLAVI.end()]),
        ("PSALTER_PAHLAVI", [ub::PSALTER_PAHLAVI.start(), ub::PSALTER_PAHLAVI.end()]),
        ("OLD_TURKIC", [ub::OLD_TURKIC.start(), ub::OLD_TURKIC.end()]),
        ("OLD_HUNGARIAN", [ub::OLD_HUNGARIAN.start(), ub::OLD_HUNGARIAN.end()]),
        ("HANIFI_ROHINGYA", [ub::HANIFI_ROHINGYA.start(), ub::HANIFI_ROHINGYA.end()]),
        ("RUMI_NUMERAL_SYMBOLS", [ub::RUMI_NUMERAL_SYMBOLS.start(), ub::RUMI_NUMERAL_SYMBOLS.end()]),
        ("YEZIDI", [ub::YEZIDI.start(), ub::YEZIDI.end()]),
        ("ARABIC_EXTENDED_C", [ub::ARABIC_EXTENDED_C.start(), ub::ARABIC_EXTENDED_C.end()]),
        ("OLD_SOGDIAN", [ub::OLD_SOGDIAN.start(), ub::OLD_SOGDIAN.end()]),
        ("SOGDIAN", [ub::SOGDIAN.start(), ub::SOGDIAN.end()]),
        ("OLD_UYGHUR", [ub::OLD_UYGHUR.start(), ub::OLD_UYGHUR.end()]),
        ("CHORASMIAN", [ub::CHORASMIAN.start(), ub::CHORASMIAN.end()]),
        ("ELYMAIC", [ub::ELYMAIC.start(), ub::ELYMAIC.end()]),
        ("BRAHMI", [ub::BRAHMI.start(), ub::BRAHMI.end()]),
        ("KAITHI", [ub::KAITHI.start(), ub::KAITHI.end()]),
        ("SORA_SOMPENG", [ub::SORA_SOMPENG.start(), ub::SORA_SOMPENG.end()]),
        ("CHAKMA", [ub::CHAKMA.start(), ub::CHAKMA.end()]),
        ("MAHAJANI", [ub::MAHAJANI.start(), ub::MAHAJANI.end()]),
        ("SHARADA", [ub::SHARADA.start(), ub::SHARADA.end()]),
        ("SINHALA_ARCHAIC_NUMBERS", [ub::SINHALA_ARCHAIC_NUMBERS.start(), ub::SINHALA_ARCHAIC_NUMBERS.end()]),
        ("KHOJKI", [ub::KHOJKI.start(), ub::KHOJKI.end()]),
        ("MULTANI", [ub::MULTANI.start(), ub::MULTANI.end()]),
        ("KHUDAWADI", [ub::KHUDAWADI.start(), ub::KHUDAWADI.end()]),
        ("GRANTHA", [ub::GRANTHA.start(), ub::GRANTHA.end()]),
        ("NEWA", [ub::NEWA.start(), ub::NEWA.end()]),
        ("TIRHUTA", [ub::TIRHUTA.start(), ub::TIRHUTA.end()]),
        ("SIDDHAM", [ub::SIDDHAM.start(), ub::SIDDHAM.end()]),
        ("MODI", [ub::MODI.start(), ub::MODI.end()]),
        ("MONGOLIAN_SUPPLEMENT", [ub::MONGOLIAN_SUPPLEMENT.start(), ub::MONGOLIAN_SUPPLEMENT.end()]),
        ("TAKRI", [ub::TAKRI.start(), ub::TAKRI.end()]),
        ("AHOM", [ub::AHOM.start(), ub::AHOM.end()]),
        ("DOGRA", [ub::DOGRA.start(), ub::DOGRA.end()]),
        ("WARANG_CITI", [ub::WARANG_CITI.start(), ub::WARANG_CITI.end()]),
        ("DIVES_AKURU", [ub::DIVES_AKURU.start(), ub::DIVES_AKURU.end()]),
        ("NANDINAGARI", [ub::NANDINAGARI.start(), ub::NANDINAGARI.end()]),
        ("ZANABAZAR_SQUARE", [ub::ZANABAZAR_SQUARE.start(), ub::ZANABAZAR_SQUARE.end()]),
        ("SOYOMBO", [ub::SOYOMBO.start(), ub::SOYOMBO.end()]),
        ("UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A", [ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A.start(), ub::UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A.end()]),
        ("PAU_CIN_HAU", [ub::PAU_CIN_HAU.start(), ub::PAU_CIN_HAU.end()]),
        ("DEVANAGARI_EXTENDED_A", [ub::DEVANAGARI_EXTENDED_A.start(), ub::DEVANAGARI_EXTENDED_A.end()]),
        ("BHAIKSUKI", [ub::BHAIKSUKI.start(), ub::BHAIKSUKI.end()]),
        ("MARCHEN", [ub::MARCHEN.start(), ub::MARCHEN.end()]),
        ("MASARAM_GONDI", [ub::MASARAM_GONDI.start(), ub::MASARAM_GONDI.end()]),
        ("GUNJALA_GONDI", [ub::GUNJALA_GONDI.start(), ub::GUNJALA_GONDI.end()]),
        ("MAKASAR", [ub::MAKASAR.start(), ub::MAKASAR.end()]),
        ("KAWI", [ub::KAWI.start(), ub::KAWI.end()]),
        ("LISU_SUPPLEMENT", [ub::LISU_SUPPLEMENT.start(), ub::LISU_SUPPLEMENT.end()]),
        ("TAMIL_SUPPLEMENT", [ub::TAMIL_SUPPLEMENT.start(), ub::TAMIL_SUPPLEMENT.end()]),
        ("CUNEIFORM", [ub::CUNEIFORM.start(), ub::CUNEIFORM.end()]),
        ("CUNEIFORM_NUMBERS_AND_PUNCTUATION", [ub::CUNEIFORM_NUMBERS_AND_PUNCTUATION.start(), ub::CUNEIFORM_NUMBERS_AND_PUNCTUATION.end()]),
        ("EARLY_DYNASTIC_CUNEIFORM", [ub::EARLY_DYNASTIC_CUNEIFORM.start(), ub::EARLY_DYNASTIC_CUNEIFORM.end()]),
        ("CYPRO_MINOAN", [ub::CYPRO_MINOAN.start(), ub::CYPRO_MINOAN.end()]),
        ("EGYPTIAN_HIEROGLYPHS", [ub::EGYPTIAN_HIEROGLYPHS.start(), ub::EGYPTIAN_HIEROGLYPHS.end()]),
        ("EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS", [ub::EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS.start(), ub::EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS.end()]),
        ("ANATOLIAN_HIEROGLYPHS", [ub::ANATOLIAN_HIEROGLYPHS.start(), ub::ANATOLIAN_HIEROGLYPHS.end()]),
        ("BAMUM_SUPPLEMENT", [ub::BAMUM_SUPPLEMENT.start(), ub::BAMUM_SUPPLEMENT.end()]),
        ("MRO", [ub::MRO.start(), ub::MRO.end()]),
        ("TANGSA", [ub::TANGSA.start(), ub::TANGSA.end()]),
        ("BASSA_VAH", [ub::BASSA_VAH.start(), ub::BASSA_VAH.end()]),
        ("PAHAWH_HMONG", [ub::PAHAWH_HMONG.start(), ub::PAHAWH_HMONG.end()]),
        ("MEDEFAIDRIN", [ub::MEDEFAIDRIN.start(), ub::MEDEFAIDRIN.end()]),
        ("MIAO", [ub::MIAO.start(), ub::MIAO.end()]),
        ("IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION", [ub::IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION.start(), ub::IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION.end()]),
        ("TANGUT", [ub::TANGUT.start(), ub::TANGUT.end()]),
        ("TANGUT_COMPONENTS", [ub::TANGUT_COMPONENTS.start(), ub::TANGUT_COMPONENTS.end()]),
        ("KHITAN_SMALL_SCRIPT", [ub::KHITAN_SMALL_SCRIPT.start(), ub::KHITAN_SMALL_SCRIPT.end()]),
        ("TANGUT_SUPPLEMENT", [ub::TANGUT_SUPPLEMENT.start(), ub::TANGUT_SUPPLEMENT.end()]),
        ("KANA_EXTENDED_B", [ub::KANA_EXTENDED_B.start(), ub::KANA_EXTENDED_B.end()]),
        ("KANA_SUPPLEMENT", [ub::KANA_SUPPLEMENT.start(), ub::KANA_SUPPLEMENT.end()]),
        ("KANA_EXTENDED_A", [ub::KANA_EXTENDED_A.start(), ub::KANA_EXTENDED_A.end()]),
        ("SMALL_KANA_EXTENSION", [ub::SMALL_KANA_EXTENSION.start(), ub::SMALL_KANA_EXTENSION.end()]),
        ("NUSHU", [ub::NUSHU.start(), ub::NUSHU.end()]),
        ("DUPLOYAN", [ub::DUPLOYAN.start(), ub::DUPLOYAN.end()]),
        ("SHORTHAND_FORMAT_CONTROLS", [ub::SHORTHAND_FORMAT_CONTROLS.start(), ub::SHORTHAND_FORMAT_CONTROLS.end()]),
        ("ZNAMENNY_MUSICAL_NOTATION", [ub::ZNAMENNY_MUSICAL_NOTATION.start(), ub::ZNAMENNY_MUSICAL_NOTATION.end()]),
        ("BYZANTINE_MUSICAL_SYMBOLS", [ub::BYZANTINE_MUSICAL_SYMBOLS.start(), ub::BYZANTINE_MUSICAL_SYMBOLS.end()]),
        ("MUSICAL_SYMBOLS", [ub::MUSICAL_SYMBOLS.start(), ub::MUSICAL_SYMBOLS.end()]),
        ("ANCIENT_GREEK_MUSICAL_NOTATION", [ub::ANCIENT_GREEK_MUSICAL_NOTATION.start(), ub::ANCIENT_GREEK_MUSICAL_NOTATION.end()]),
        ("KAKTOVIK_NUMERALS", [ub::KAKTOVIK_NUMERALS.start(), ub::KAKTOVIK_NUMERALS.end()]),
        ("MAYAN_NUMERALS", [ub::MAYAN_NUMERALS.start(), ub::MAYAN_NUMERALS.end()]),
        ("TAI_XUAN_JING_SYMBOLS", [ub::TAI_XUAN_JING_SYMBOLS.start(), ub::TAI_XUAN_JING_SYMBOLS.end()]),
        ("COUNTING_ROD_NUMERALS", [ub::COUNTING_ROD_NUMERALS.start(), ub::COUNTING_ROD_NUMERALS.end()]),
        ("MATHEMATICAL_ALPHANUMERIC_SYMBOLS", [ub::MATHEMATICAL_ALPHANUMERIC_SYMBOLS.start(), ub::MATHEMATICAL_ALPHANUMERIC_SYMBOLS.end()]),
        ("SUTTON_SIGNWRITING", [ub::SUTTON_SIGNWRITING.start(), ub::SUTTON_SIGNWRITING.end()]),
        ("LATIN_EXTENDED_G", [ub::LATIN_EXTENDED_G.start(), ub::LATIN_EXTENDED_G.end()]),
        ("GLAGOLITIC_SUPPLEMENT", [ub::GLAGOLITIC_SUPPLEMENT.start(), ub::GLAGOLITIC_SUPPLEMENT.end()]),
        ("CYRILLIC_EXTENDED_D", [ub::CYRILLIC_EXTENDED_D.start(), ub::CYRILLIC_EXTENDED_D.end()]),
        ("NYIAKENG_PUACHUE_HMONG", [ub::NYIAKENG_PUACHUE_HMONG.start(), ub::NYIAKENG_PUACHUE_HMONG.end()]),
        ("TOTO", [ub::TOTO.start(), ub::TOTO.end()]),
        ("WANCHO", [ub::WANCHO.start(), ub::WANCHO.end()]),
        ("NAG_MUNDARI", [ub::NAG_MUNDARI.start(), ub::NAG_MUNDARI.end()]),
        ("ETHIOPIC_EXTENDED_B", [ub::ETHIOPIC_EXTENDED_B.start(), ub::ETHIOPIC_EXTENDED_B.end()]),
        ("MENDE_KIKAKUI", [ub::MENDE_KIKAKUI.start(), ub::MENDE_KIKAKUI.end()]),
        ("ADLAM", [ub::ADLAM.start(), ub::ADLAM.end()]),
        ("INDIC_SIYAQ_NUMBERS", [ub::INDIC_SIYAQ_NUMBERS.start(), ub::INDIC_SIYAQ_NUMBERS.end()]),
        ("OTTOMAN_SIYAQ_NUMBERS", [ub::OTTOMAN_SIYAQ_NUMBERS.start(), ub::OTTOMAN_SIYAQ_NUMBERS.end()]),
        ("ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS", [ub::ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS.start(), ub::ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS.end()]),
        ("MAHJONG_TILES", [ub::MAHJONG_TILES.start(), ub::MAHJONG_TILES.end()]),
        ("DOMINO_TILES", [ub::DOMINO_TILES.start(), ub::DOMINO_TILES.end()]),
        ("PLAYING_CARDS", [ub::PLAYING_CARDS.start(), ub::PLAYING_CARDS.end()]),
        ("ENCLOSED_ALPHANUMERIC_SUPPLEMENT", [ub::ENCLOSED_ALPHANUMERIC_SUPPLEMENT.start(), ub::ENCLOSED_ALPHANUMERIC_SUPPLEMENT.end()]),
        ("ENCLOSED_IDEOGRAPHIC_SUPPLEMENT", [ub::ENCLOSED_IDEOGRAPHIC_SUPPLEMENT.start(), ub::ENCLOSED_IDEOGRAPHIC_SUPPLEMENT.end()]),
        ("MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS", [ub::MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS.start(), ub::MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS.end()]),
        ("EMOTICONS", [ub::EMOTICONS.start(), ub::EMOTICONS.end()]),
        ("ORNAMENTAL_DINGBATS", [ub::ORNAMENTAL_DINGBATS.start(), ub::ORNAMENTAL_DINGBATS.end()]),
        ("TRANSPORT_AND_MAP_SYMBOLS", [ub::TRANSPORT_AND_MAP_SYMBOLS.start(), ub::TRANSPORT_AND_MAP_SYMBOLS.end()]),
        ("ALCHEMICAL_SYMBOLS", [ub::ALCHEMICAL_SYMBOLS.start(), ub::ALCHEMICAL_SYMBOLS.end()]),
        ("GEOMETRIC_SHAPES_EXTENDED", [ub::GEOMETRIC_SHAPES_EXTENDED.start(), ub::GEOMETRIC_SHAPES_EXTENDED.end()]),
        ("SUPPLEMENTAL_ARROWS_C", [ub::SUPPLEMENTAL_ARROWS_C.start(), ub::SUPPLEMENTAL_ARROWS_C.end()]),
        ("SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS", [ub::SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS.start(), ub::SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS.end()]),
        ("CHESS_SYMBOLS", [ub::CHESS_SYMBOLS.start(), ub::CHESS_SYMBOLS.end()]),
        ("SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A", [ub::SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A.start(), ub::SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A.end()]),
        ("SYMBOLS_FOR_LEGACY_COMPUTING", [ub::SYMBOLS_FOR_LEGACY_COMPUTING.start(), ub::SYMBOLS_FOR_LEGACY_COMPUTING.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I.end()]),
        ("CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT", [ub::CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT.start(), ub::CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G.end()]),
        ("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H", [ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H.start(), ub::CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H.end()]),
        ("TAGS", [ub::TAGS.start(), ub::TAGS.end()]),
        ("VARIATION_SELECTORS_SUPPLEMENT", [ub::VARIATION_SELECTORS_SUPPLEMENT.start(), ub::VARIATION_SELECTORS_SUPPLEMENT.end()]),
        ("SUPPLEMENTARY_PRIVATE_USE_AREA_A", [ub::SUPPLEMENTARY_PRIVATE_USE_AREA_A.start(), ub::SUPPLEMENTARY_PRIVATE_USE_AREA_A.end()]),
        ("SUPPLEMENTARY_PRIVATE_USE_AREA_B", [ub::SUPPLEMENTARY_PRIVATE_USE_AREA_B.start(), ub::SUPPLEMENTARY_PRIVATE_USE_AREA_B.end()]),
    ]);
}
