name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: texhigh.exe
            package_ext: zip
            profile: release-windows
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: texhigh
            package_ext: tar.gz
            profile: release
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: texhigh
            package_ext: tar.gz
            profile: release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        targets: ${{ matrix.target }}

    - name: Add Windows target (if needed)
      if: matrix.os == 'windows-latest'
      run: rustup target add ${{ matrix.target }}

    - name: Build project
      run: cargo build --profile ${{ matrix.profile }} --target ${{ matrix.target }} --verbose
      env:
        RUSTFLAGS: -C target-feature=+crt-static

    - name: Create output directory
      run: mkdir release-package

    - name: Prepare Windows artifacts
      if: matrix.os == 'windows-latest'
      run: |
        Copy-Item "target\${{ matrix.target }}\${{ matrix.profile }}\${{ matrix.artifact_name }}" release-package/
        7z a -tzip texhigh-${{ matrix.target }}.zip ./release-package/*

    - name: Prepare Unix artifacts
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: |
        cp "target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.artifact_name }}" release-package/
        chmod +x release-package/${{ matrix.artifact_name }}
        tar czf texhigh-${{ matrix.target }}.tar.gz -C release-package .

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: texhigh-${{ matrix.target }}.${{ matrix.package_ext }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
